services:
  eng_project:
    container_name: eng_project
    build:
      context: ./
    image: patlew/eng_project:latest
    network_mode: host
    volumes:
      - ~/plewicka_ws:/mnt/ws
    command: bash
    env_file: env
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]